import { NextRequest } from "next/server";
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/db", () => ({ db: {} }));
vi.mock("@/lib/storage", () => ({ storageAdapter: {} }));
vi.mock("@/lib/accounts/api-session", () => ({
  requireAdminRequest: vi.fn(),
}));
vi.mock("@/lib/submissions/publisher", async () => {
  const actual = await vi.importActual<
    typeof import("@/lib/submissions/publisher")
  >("@/lib/submissions/publisher");
  return { ...actual, publishSubmission: vi.fn() };
});
vi.mock("@/lib/submissions/reconciliation", async () => {
  const actual = await vi.importActual<
    typeof import("@/lib/submissions/reconciliation")
  >("@/lib/submissions/reconciliation");
  return {
    ...actual,
    createManualSubmission: vi.fn(),
    editSubmissionField: vi.fn(),
    reviewSubmissionField: vi.fn(),
    transitionSubmission: vi.fn(),
  };
});
vi.mock("@/lib/submissions/media", async () => {
  const actual = await vi.importActual<
    typeof import("@/lib/submissions/media")
  >("@/lib/submissions/media");
  return {
    ...actual,
    addSubmissionImage: vi.fn(),
    reviewSubmissionMedia: vi.fn(),
  };
});

const { requireAdminRequest } = await import("@/lib/accounts/api-session");
const { publishSubmission, SubmissionPublishError } =
  await import("@/lib/submissions/publisher");
const {
  createManualSubmission,
  editSubmissionField,
  ReconciliationError,
  reviewSubmissionField,
  transitionSubmission,
} = await import("@/lib/submissions/reconciliation");
const { addSubmissionImage, reviewSubmissionMedia, SubmissionMediaError } =
  await import("@/lib/submissions/media");

const create = await import("./route");
const editField = await import("./[id]/fields/[fieldKey]/route");
const reviewField = await import("./[id]/fields/[fieldKey]/review/route");
const media = await import("./[id]/media/route");
const reviewMedia = await import("./[id]/media/[mediaId]/review/route");
const review = await import("./[id]/review/route");
const publish = await import("./[id]/publish/route");

const ID = "11111111-1111-1111-1111-111111111111";
const json = (body: unknown, method = "POST") =>
  new NextRequest("http://localhost/x", {
    method,
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
const multipart = (entries: Record<string, string | Blob>) => {
  const form = new FormData();
  for (const [key, value] of Object.entries(entries)) form.set(key, value);
  return new NextRequest("http://localhost/x", { method: "POST", body: form });
};
// The routes' typed `RouteContext` params are generated by Next; the tests only
// need the runtime shape.
const ctx = (params: Record<string, string>) =>
  ({ params: Promise.resolve(params) }) as never;

const owner = { userId: "u1", permissionLevel: "owner" as const };
const verifier = { userId: "u2", permissionLevel: "verifier" as const };

const routes: [string, () => Promise<Response>][] = [
  ["POST /submissions", () => create.POST(json({ developerId: ID }))],
  [
    "PATCH /submissions/{id}/fields/{key}",
    () =>
      editField.PATCH(
        json({ value: "x" }, "PATCH"),
        ctx({ id: ID, fieldKey: "property.name" }),
      ),
  ],
  [
    "POST /submissions/{id}/fields/{key}/review",
    () =>
      reviewField.POST(
        json({ reviewStatus: "confirmed" }),
        ctx({ id: ID, fieldKey: "property.name" }),
      ),
  ],
  [
    "POST /submissions/{id}/media",
    () => media.POST(multipart({ mediaType: "photo" }), ctx({ id: ID })),
  ],
  [
    "POST /submissions/{id}/media/{mediaId}/review",
    () =>
      reviewMedia.POST(
        json({ reviewStatus: "confirmed", isPublic: true }),
        ctx({ id: ID, mediaId: ID }),
      ),
  ],
  [
    "POST /submissions/{id}/review",
    () => review.POST(json({ action: "approve" }), ctx({ id: ID })),
  ],
  [
    "POST /submissions/{id}/publish",
    () => publish.POST(json({}), ctx({ id: ID })),
  ],
];

beforeEach(() => {
  vi.clearAllMocks();
});

describe("admin submission routes: authentication", () => {
  it.each(routes)("%s needs a session", async (_name, call) => {
    vi.mocked(requireAdminRequest).mockResolvedValue("unauthenticated");
    expect((await call()).status).toBe(401);
  });

  it.each(routes)("%s refuses a signed-in non-admin", async (_name, call) => {
    vi.mocked(requireAdminRequest).mockResolvedValue("forbidden");
    expect((await call()).status).toBe(403);
  });

  it("does nothing on a refused request", async () => {
    vi.mocked(requireAdminRequest).mockResolvedValue("forbidden");
    for (const [, call] of routes) await call();
    expect(createManualSubmission).not.toHaveBeenCalled();
    expect(editSubmissionField).not.toHaveBeenCalled();
    expect(reviewSubmissionField).not.toHaveBeenCalled();
    expect(transitionSubmission).not.toHaveBeenCalled();
    expect(addSubmissionImage).not.toHaveBeenCalled();
    expect(reviewSubmissionMedia).not.toHaveBeenCalled();
    expect(publishSubmission).not.toHaveBeenCalled();
  });
});

describe("publish", () => {
  it("is for owners only, even though verifiers are admins", async () => {
    vi.mocked(requireAdminRequest).mockResolvedValue(verifier);
    const response = await publish.POST(json({}), ctx({ id: ID }));
    expect(response.status).toBe(403);
    expect((await response.json()).error.code).toBe("owner_required");
    expect(publishSubmission).not.toHaveBeenCalled();
  });

  it("publishes as the owner and returns the result uncached", async () => {
    vi.mocked(requireAdminRequest).mockResolvedValue(owner);
    vi.mocked(publishSubmission).mockResolvedValue({
      propertyId: "p",
    } as never);
    const response = await publish.POST(json({}), ctx({ id: ID }));
    expect(response.status).toBe(200);
    expect(response.headers.get("Cache-Control")).toBe("no-store");
    expect(publishSubmission).toHaveBeenCalledWith({
      submissionId: ID,
      actorUserId: "u1",
      actorRole: "owner",
    });
  });

  it("reports a submission that cannot be published as a conflict, not a crash", async () => {
    vi.mocked(requireAdminRequest).mockResolvedValue(owner);
    vi.mocked(publishSubmission).mockRejectedValue(
      new SubmissionPublishError("not approved"),
    );
    const response = await publish.POST(json({}), ctx({ id: ID }));
    expect(response.status).toBe(409);
    expect((await response.json()).error.code).toBe("cannot_publish");
  });
});

describe("review actions", () => {
  it("passes the admin's own permission level to the state machine", async () => {
    vi.mocked(requireAdminRequest).mockResolvedValue(verifier);
    vi.mocked(transitionSubmission).mockResolvedValue();
    const response = await review.POST(
      json({ action: "start_review" }),
      ctx({ id: ID }),
    );
    expect(response.status).toBe(204);
    expect(transitionSubmission).toHaveBeenCalledWith(
      expect.anything(),
      expect.objectContaining({
        action: "start_review",
        actorUserId: "u2",
        actorRole: "verifier",
      }),
    );
  });

  it("does not offer publish through this route, and rejects unknown actions", async () => {
    vi.mocked(requireAdminRequest).mockResolvedValue(owner);
    for (const action of ["publish", "delete", 5, undefined]) {
      const response = await review.POST(json({ action }), ctx({ id: ID }));
      expect(response.status).toBe(422);
    }
    expect(transitionSubmission).not.toHaveBeenCalled();
  });

  it("maps a refused transition to a conflict and a missing submission to 404", async () => {
    vi.mocked(requireAdminRequest).mockResolvedValue(verifier);
    vi.mocked(transitionSubmission).mockRejectedValueOnce(
      new ReconciliationError("transition_not_allowed", "no"),
    );
    expect(
      (await review.POST(json({ action: "submit" }), ctx({ id: ID }))).status,
    ).toBe(409);
    vi.mocked(transitionSubmission).mockRejectedValueOnce(
      new ReconciliationError("submission_not_found", "gone"),
    );
    expect(
      (await review.POST(json({ action: "approve" }), ctx({ id: ID }))).status,
    ).toBe(404);
  });
});

describe("field and media routes", () => {
  beforeEach(() => vi.mocked(requireAdminRequest).mockResolvedValue(owner));

  it("creates a manual draft, and needs a developer id", async () => {
    vi.mocked(createManualSubmission).mockResolvedValue({ submissionId: "s" });
    const ok = await create.POST(json({ developerId: ID }));
    expect(ok.status).toBe(201);
    expect(await ok.json()).toEqual({ submissionId: "s" });
    expect((await create.POST(json({}))).status).toBe(422);

    vi.mocked(createManualSubmission).mockRejectedValueOnce(
      new ReconciliationError("developer_not_found", "no such developer"),
    );
    expect((await create.POST(json({ developerId: ID }))).status).toBe(404);
  });

  it("maps field-edit failures to the right status", async () => {
    const call = () =>
      editField.PATCH(
        json({ value: 1 }, "PATCH"),
        ctx({ id: ID, fieldKey: "property.name" }),
      );
    vi.mocked(editSubmissionField).mockResolvedValueOnce();
    expect((await call()).status).toBe(204);
    for (const [code, status] of [
      ["invalid_value", 422],
      ["invalid_state", 409],
      ["field_not_found", 404],
      ["submission_not_found", 404],
    ] as const) {
      vi.mocked(editSubmissionField).mockRejectedValueOnce(
        new ReconciliationError(code, code),
      );
      expect((await call()).status).toBe(status);
    }
    expect(
      (
        await editField.PATCH(
          json({}, "PATCH"),
          ctx({ id: ID, fieldKey: "property.name" }),
        )
      ).status,
    ).toBe(422);
  });

  it("validates review decisions before touching anything", async () => {
    const bad = await reviewField.POST(
      json({ reviewStatus: "edited" }),
      ctx({ id: ID, fieldKey: "property.name" }),
    );
    expect(bad.status).toBe(422);
    const badMedia = await reviewMedia.POST(
      json({ reviewStatus: "confirmed" }),
      ctx({ id: ID, mediaId: ID }),
    );
    expect(badMedia.status).toBe(422);
    expect(reviewSubmissionField).not.toHaveBeenCalled();
    expect(reviewSubmissionMedia).not.toHaveBeenCalled();
  });

  it("uploads an image only with the full set of required details", async () => {
    vi.mocked(addSubmissionImage).mockResolvedValue({ id: "m" });
    const file = new Blob([new Uint8Array([1])], { type: "image/png" });
    const full = {
      file,
      mediaType: "photo",
      sourceKind: "own",
      attribution: "Us",
    };
    const ok = await media.POST(multipart(full), ctx({ id: ID }));
    expect(ok.status).toBe(201);

    for (const missing of ["file", "mediaType", "sourceKind", "attribution"]) {
      const entries = { ...full } as Record<string, string | Blob>;
      delete entries[missing];
      expect(
        (await media.POST(multipart(entries), ctx({ id: ID }))).status,
      ).toBe(422);
    }
    // A brochure-derived kind can only come from the extraction path, never an upload.
    expect(
      (
        await media.POST(
          multipart({ ...full, sourceKind: "developer_brochure" }),
          ctx({ id: ID }),
        )
      ).status,
    ).toBe(422);

    vi.mocked(addSubmissionImage).mockRejectedValueOnce(
      new SubmissionMediaError("invalid_state", "locked"),
    );
    expect((await media.POST(multipart(full), ctx({ id: ID }))).status).toBe(
      409,
    );
  });
});
